/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v15.0
processor: MIMXRT1021xxxxx
package_id: MIMXRT1021DAF5B
mcu_data: ksdk2_0
processor_version: 15.0.1
board: MIMXRT1020-EVK
pin_labels:
- {pin_num: '30', pin_signal: ONOFF, label: ONOFF}
- {pin_num: '33', pin_signal: PMIC_ON_REQ, label: PMIC_ON_REQ}
- {pin_num: '32', pin_signal: TEST_MODE, label: GND}
- {pin_num: '42', pin_signal: USB_OTG1_DP, label: 'SD1_D1/J15[8]', identifier: SD1_D1}
- {pin_num: '41', pin_signal: USB_OTG1_DN, label: 'SD_CD_SW/J15[9]', identifier: SD_CD_SW}
- {pin_num: '19', pin_signal: VSS0, label: GND}
- {pin_num: '29', pin_signal: VSS1, label: GND}
- {pin_num: '39', pin_signal: VSS2, label: GND}
- {pin_num: '49', pin_signal: VSS3, label: GND}
- {pin_num: '59', pin_signal: VSS4, label: GND}
- {pin_num: '70', pin_signal: VSS5, label: GND}
- {pin_num: '79', pin_signal: VSS6, label: GND}
- {pin_num: '92', pin_signal: VSS7, label: SAI1_MCLK}
- {pin_num: '7', pin_signal: GPIO_EMC_04, label: 'SEMC_CAS/U14[17]', identifier: SEMC_CAS}
- {pin_num: '18', pin_signal: VDD_SOC_IN0, label: 'SEMC_D0/U14[2]', identifier: SEMC_D0}
- {pin_num: '28', pin_signal: VDD_SOC_IN1, label: VDD_SOC_IN}
- {pin_num: '69', pin_signal: VDD_SOC_IN2, label: VDD_SOC_IN}
- {pin_num: '81', pin_signal: VDD_SOC_IN3, label: 'UART_RX/J17[1]'}
- {pin_num: '91', pin_signal: VDD_SOC_IN4, label: SAI1_TX_BCLK}
- {pin_num: '44', pin_signal: VDD_HIGH_CAP, label: NVCC_SD}
- {pin_num: '35', pin_signal: VDD_SNVS_CAP, label: GND}
- {pin_num: '48', pin_signal: VDD_HIGH_IN, label: 'SD1_D2/J15[1]', identifier: SD1_D2}
- {pin_num: '34', pin_signal: VDD_SNVS_IN, label: VDD_SNVS_IN}
- {pin_num: '50', pin_signal: NVCC_PLL, label: VDDA_1P1_CAP}
- {pin_num: '5', pin_signal: NVCC_GPIO0, label: NVCC_GPIO_3V3}
- {pin_num: '20', pin_signal: NVCC_GPIO1, label: NVCC_GPIO_3V3}
- {pin_num: '58', pin_signal: NVCC_GPIO2, label: NVCC_GPIO_3V3}
- {pin_num: '38', pin_signal: USB_OTG1_VBUS, label: 5V_USB_OTG}
- {pin_num: '43', pin_signal: NGND_KEL0, label: 'SD1_D0/J15[7]', identifier: SD1_D0}
- {pin_num: '51', pin_signal: VDDA_ADC_3P3, label: VDDA_ADC_3P3_MCU}
- {pin_num: '40', pin_signal: VDD_USB_CAP, label: VDD_USB_3V}
- {pin_num: '27', pin_signal: DCDC_IN_Q, label: MCU_DCDC_IN_3V3}
- {pin_num: '52', pin_signal: GPIO_AD_B1_15, label: 'I2C1_SDA/U10[18]/J18[5]'}
- {pin_num: '23', pin_signal: DCDC_IN, label: MCU_DCDC_IN_3V3}
- {pin_num: '25', pin_signal: DCDC_LP, label: DCDC_OUT}
- {pin_num: '24', pin_signal: DCDC_GND, label: GND}
- {pin_num: '26', pin_signal: DCDC_PSWITCH, label: MCU_DCDC_IN_3V3}
- {pin_num: '54', pin_signal: GPIO_AD_B1_13, label: 'CAN_STBY/J18[4]', identifier: CAN_STBY}
- {pin_num: '17', pin_signal: GPIO_SD_B1_02, label: I2C4_SCL}
- {pin_num: '16', pin_signal: GPIO_SD_B1_03, label: I2C4_SDA}
- {pin_num: '15', pin_signal: GPIO_SD_B1_04, label: INT1_COMBO}
- {pin_num: '6', pin_signal: GPIO_EMC_05, label: 'SEMC_D5/U14[10]', identifier: SEMC_D5;RESET}
- {pin_num: '4', pin_signal: GPIO_EMC_06, label: 'SEMC_RAS/U14[18]', identifier: SEMC_RAS}
- {pin_num: '3', pin_signal: GPIO_EMC_07, label: 'SEMC_CS0/U14[19]', identifier: SEMC_CS0}
- {pin_num: '2', pin_signal: GPIO_EMC_08, label: 'SEMC_BA0/U14[20]', identifier: SEMC_BA0}
- {pin_num: '1', pin_signal: GPIO_EMC_09, label: 'SEMC_BA1/U14[21]', identifier: SEMC_BA1}
- {pin_num: '100', pin_signal: GPIO_EMC_16, label: 'SEMC_A0/U14[23]/BOOT_MODE[0]', identifier: SEMC_A0}
- {pin_num: '99', pin_signal: GPIO_EMC_17, label: 'SEMC_A1/U14[24]/BOOT_MODE[1]', identifier: SEMC_A1}
- {pin_num: '98', pin_signal: GPIO_EMC_18, label: 'SEMC_A2/U14[25]/BT_CFG[0]', identifier: SEMC_A2}
- {pin_num: '97', pin_signal: GPIO_EMC_19, label: 'SEMC_A3/U14[26]/BT_CFG[1]', identifier: SEMC_A3;PINSWDIO}
- {pin_num: '96', pin_signal: GPIO_EMC_20, label: 'SEMC_A4/U14[29]/BT_CFG[2]', identifier: SEMC_A4;PINSWDCLK}
- {pin_num: '94', pin_signal: GPIO_EMC_21, label: 'SEMC_A5/U14[30]/BT_CFG[3]', identifier: SEMC_A5}
- {pin_num: '93', pin_signal: GPIO_EMC_22, label: 'SEMC_A6/U14[31]/BT_CFG[4]', identifier: SEMC_A6}
- {pin_num: '90', pin_signal: GPIO_EMC_23, label: 'SAI1_TX_SYNC/J19[10]'}
- {pin_num: '89', pin_signal: GPIO_EMC_24, label: 'SAI1_TXD/J19[9]'}
- {pin_num: '88', pin_signal: GPIO_EMC_25, label: AUD_INT}
- {pin_num: '87', pin_signal: GPIO_EMC_26, label: SAI1_RXD}
- {pin_num: '86', pin_signal: GPIO_EMC_27, label: 'SEMC_A12/U14[36]/BT_CFG[9]', identifier: SEMC_A12}
- {pin_num: '85', pin_signal: GPIO_EMC_32, label: 'SEMC_D8/U14[42]', identifier: SEMC_D8}
- {pin_num: '84', pin_signal: GPIO_EMC_33, label: 'ENET_INT/U11[21]/J17[8]', identifier: ENET_INT}
- {pin_num: '83', pin_signal: GPIO_EMC_34, label: 'SD0_VSELECT/J19[1]'}
- {pin_num: '82', pin_signal: GPIO_EMC_35, label: 'UART_TX/J17[2]'}
- {pin_num: '95', pin_signal: NVCC_GPIO5, label: NVCC_GPIO_3V3}
- {pin_num: '80', pin_signal: NVCC_GPIO4, label: NVCC_GPIO_3V3}
- {pin_num: '71', pin_signal: NVCC_GPIO3, label: NVCC_GPIO_3V3}
- {pin_num: '78', pin_signal: GPIO_AD_B0_00, label: 'JTAG_TMS/J16[7]/SWD_DIO'}
- {pin_num: '77', pin_signal: GPIO_AD_B0_01, label: 'JTAG_TCK/J16[9]/SWD_CLK'}
- {pin_num: '76', pin_signal: GPIO_AD_B0_02, label: GND}
- {pin_num: '75', pin_signal: GPIO_AD_B0_03, label: 'JTAG_TDI/J16[5]/WDOG_B'}
- {pin_num: '74', pin_signal: GPIO_AD_B0_04, label: 'JTAG_TDO/J16[13]/ENET_RST/U11[32]', identifier: ENET_RST}
- {pin_num: '73', pin_signal: GPIO_AD_B0_05, label: 'JTAG_nTRST/J16[3]/USER_LED/J17[5]'}
- {pin_num: '72', pin_signal: GPIO_AD_B0_06, label: 'UART1_TXD/J17[6]', identifier: UART1_TXD}
- {pin_num: '68', pin_signal: GPIO_AD_B0_07, label: 'UART1_RXD/J17[4]', identifier: UART1_RXD}
- {pin_num: '67', pin_signal: GPIO_AD_B0_08, label: 'ENET_TX_CLK/U11[9]', identifier: ENET_TX_CLK}
- {pin_num: '66', pin_signal: GPIO_AD_B0_09, label: 'ENET_RXD1/U11[15]/J17[3]', identifier: ENET_RXD1}
- {pin_num: '65', pin_signal: GPIO_AD_B0_10, label: 'ENET_RXD0/U11[16]/J19[6]', identifier: ENET_RXD0}
- {pin_num: '64', pin_signal: GPIO_AD_B0_11, label: 'ENET_CRS_DV/U11[18]/J19[3]', identifier: ENET_CRS_DV}
- {pin_num: '63', pin_signal: GPIO_AD_B0_12, label: 'ENET_RXER/U11[20]/J19[4]', identifier: ENET_RXER}
- {pin_num: '62', pin_signal: GPIO_AD_B0_13, label: 'ENET_TXEN/U11[23]/J19[5]', identifier: ENET_TXEN}
- {pin_num: '61', pin_signal: GPIO_AD_B0_14, label: 'ENET_TXD0/U11[24]/J17[7]', identifier: ENET_TXD0}
- {pin_num: '60', pin_signal: GPIO_AD_B0_15, label: 'ENET_TXD1/U11[25]/J19[2]', identifier: ENET_TXD1}
- {pin_num: '57', pin_signal: GPIO_AD_B1_10, label: 'USB_OTG1_PWR/J18[1]'}
- {pin_num: '56', pin_signal: GPIO_AD_B1_11, label: 'USB_OTG1_ID/J18[2]'}
- {pin_num: '55', pin_signal: GPIO_AD_B1_12, label: 'USB_OTG1_OC/J18[3]'}
- {pin_num: '53', pin_signal: GPIO_AD_B1_14, label: 'I2C1_SCL/U10[17]/J18[6]'}
- {pin_num: '47', pin_signal: XTALO, label: XTALO}
- {pin_num: '46', pin_signal: XTALI, label: XTALI}
- {pin_num: '45', pin_signal: USB_OTG1_CHD_B, label: 'SD1_CLK/J15[5]', identifier: SD1_CLK}
- {pin_num: '22', pin_signal: GPIO_SD_B1_00, label: 'CAN1_TX/U9[1]', identifier: CAN1_TX}
- {pin_num: '21', pin_signal: GPIO_SD_B1_01, label: 'CAN1_RX/U9[4]', identifier: CAN1_RX}
- {pin_num: '13', pin_signal: GPIO_SD_B1_06, label: 'FlexSPI_D3_A/U13[7]', identifier: FlexSPI_D3_A}
- {pin_num: '14', pin_signal: GPIO_SD_B1_05, label: INT2_COMBO}
- {pin_num: '12', pin_signal: GPIO_SD_B1_07, label: 'FlexSPI_CLK/U13[6]', identifier: FlexSPI_CLK}
- {pin_num: '11', pin_signal: GPIO_SD_B1_08, label: 'FlexSPI_D0_A/U13[5]', identifier: FlexSPI_D0_A}
- {pin_num: '10', pin_signal: GPIO_SD_B1_09, label: 'FlexSPI_D2_A/U13[3]', identifier: FlexSPI_D2_A}
- {pin_num: '9', pin_signal: GPIO_SD_B1_10, label: 'FlexSPI_D1_A/U13[2]', identifier: FlexSPI_D1_A}
- {pin_num: '8', pin_signal: GPIO_SD_B1_11, label: 'FlexSPI_SS0/U13[1]', identifier: FlexSPI_SS0}
- {pin_num: '31', pin_signal: POR_B, label: 'POR_B/J16[5]/RST_TGTMCU_B/J20[3]'}
- {pin_num: '36', pin_signal: RTC_XTALI, label: RTC_XTALI}
- {pin_num: '37', pin_signal: RTC_XTALO, label: RTC_XTALO}
power_domains: {NVCC_GPIO: '3.3'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
    BOARD_InitDEBUG_UARTPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '96', peripheral: GPIO2, signal: 'gpio_io, 20', pin_signal: GPIO_EMC_20, identifier: PINSWDCLK}
  - {pin_num: '97', peripheral: GPIO2, signal: 'gpio_io, 19', pin_signal: GPIO_EMC_19, identifier: PINSWDIO}
  - {pin_num: '6', peripheral: GPIO2, signal: 'gpio_io, 05', pin_signal: GPIO_EMC_05, identifier: RESET, direction: OUTPUT, gpio_init_state: 'true'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  /* GPIO configuration of RESET on GPIO_EMC_05 (pin 6) */
  gpio_pin_config_t RESET_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_05 (pin 6) */
  GPIO_PinInit(GPIO2, 5U, &RESET_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_05_GPIO2_IO05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_19_GPIO2_IO19, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_20_GPIO2_IO20, 0U); 
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDEBUG_UARTPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '68', peripheral: LPUART1, signal: RX, pin_signal: GPIO_AD_B0_07}
  - {pin_num: '72', peripheral: LPUART1, signal: TX, pin_signal: GPIO_AD_B0_06}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDEBUG_UARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDEBUG_UARTPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_06_LPUART1_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_07_LPUART1_RX, 0U); 
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSDRAMPins:
- options: {coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSDRAMPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSDRAMPins(void) {
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitCANPins:
- options: {coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitCANPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitCANPins(void) {
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitENETPins:
- options: {coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitENETPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitENETPins(void) {
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitUSDHCPins:
- options: {coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUSDHCPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitUSDHCPins(void) {
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitQSPIPins:
- options: {coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '12', peripheral: FLEXSPI, signal: FLEXSPI_A_SCLK, pin_signal: GPIO_SD_B1_07}
  - {pin_num: '11', peripheral: FLEXSPI, signal: FLEXSPI_A_DATA0, pin_signal: GPIO_SD_B1_08}
  - {pin_num: '9', peripheral: FLEXSPI, signal: FLEXSPI_A_DATA1, pin_signal: GPIO_SD_B1_10}
  - {pin_num: '10', peripheral: FLEXSPI, signal: FLEXSPI_A_DATA2, pin_signal: GPIO_SD_B1_09}
  - {pin_num: '13', peripheral: FLEXSPI, signal: FLEXSPI_A_DATA3, pin_signal: GPIO_SD_B1_06}
  - {pin_num: '8', peripheral: FLEXSPI, signal: FLEXSPI_A_SS0_B, pin_signal: GPIO_SD_B1_11}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitQSPIPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitQSPIPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_06_FLEXSPI_A_DATA03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_07_FLEXSPI_A_SCLK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_08_FLEXSPI_A_DATA00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_09_FLEXSPI_A_DATA02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_10_FLEXSPI_A_DATA01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_11_FLEXSPI_A_SS0_B, 0U); 
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
