/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_EMC_20 (number 96), SEMC_A4/U14[29]/BT_CFG[2] */
/* Routed pin properties */
#define BOARD_INITPINS_PINSWDCLK_PERIPHERAL                                GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_PINSWDCLK_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_PINSWDCLK_CHANNEL                                     20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PINSWDCLK_GPIO                                      GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_PINSWDCLK_GPIO_PIN                                    20U   /*!< GPIO pin number */
#define BOARD_INITPINS_PINSWDCLK_GPIO_PIN_MASK                       (1U << 20U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_PINSWDCLK_PORT                                      GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_PINSWDCLK_PIN                                         20U   /*!< PORT pin number */
#define BOARD_INITPINS_PINSWDCLK_PIN_MASK                            (1U << 20U)   /*!< PORT pin mask */

/* GPIO_EMC_19 (number 97), SEMC_A3/U14[26]/BT_CFG[1] */
/* Routed pin properties */
#define BOARD_INITPINS_PINSWDIO_PERIPHERAL                                 GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_PINSWDIO_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_PINSWDIO_CHANNEL                                      19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PINSWDIO_GPIO                                       GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_PINSWDIO_GPIO_PIN                                     19U   /*!< GPIO pin number */
#define BOARD_INITPINS_PINSWDIO_GPIO_PIN_MASK                        (1U << 19U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_PINSWDIO_PORT                                       GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_PINSWDIO_PIN                                          19U   /*!< PORT pin number */
#define BOARD_INITPINS_PINSWDIO_PIN_MASK                             (1U << 19U)   /*!< PORT pin mask */

/* GPIO_EMC_05 (number 6), SEMC_D5/U14[10] */
/* Routed pin properties */
#define BOARD_INITPINS_RESET_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_RESET_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_RESET_CHANNEL                                          5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RESET_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_RESET_GPIO_PIN                                         5U   /*!< GPIO pin number */
#define BOARD_INITPINS_RESET_GPIO_PIN_MASK                            (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_RESET_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_RESET_PIN                                              5U   /*!< PORT pin number */
#define BOARD_INITPINS_RESET_PIN_MASK                                 (1U << 5U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/* GPIO_AD_B0_07 (number 68), UART1_RXD/J17[4] */
/* Routed pin properties */
#define BOARD_INITDEBUG_UARTPINS_UART1_RXD_PERIPHERAL                    LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UARTPINS_UART1_RXD_SIGNAL                             RX   /*!< Signal name */

/* GPIO_AD_B0_06 (number 72), UART1_TXD/J17[6] */
/* Routed pin properties */
#define BOARD_INITDEBUG_UARTPINS_UART1_TXD_PERIPHERAL                    LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UARTPINS_UART1_TXD_SIGNAL                             TX   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSDRAMPins(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCANPins(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitENETPins(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUSDHCPins(void);

/* GPIO_SD_B1_07 (number 12), FlexSPI_CLK/U13[6] */
/* Routed pin properties */
#define BOARD_INITQSPIPINS_FlexSPI_CLK_PERIPHERAL                        FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPIPINS_FlexSPI_CLK_SIGNAL                     FLEXSPI_A_SCLK   /*!< Signal name */

/* GPIO_SD_B1_08 (number 11), FlexSPI_D0_A/U13[5] */
/* Routed pin properties */
#define BOARD_INITQSPIPINS_FlexSPI_D0_A_PERIPHERAL                       FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPIPINS_FlexSPI_D0_A_SIGNAL                   FLEXSPI_A_DATA0   /*!< Signal name */

/* GPIO_SD_B1_10 (number 9), FlexSPI_D1_A/U13[2] */
/* Routed pin properties */
#define BOARD_INITQSPIPINS_FlexSPI_D1_A_PERIPHERAL                       FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPIPINS_FlexSPI_D1_A_SIGNAL                   FLEXSPI_A_DATA1   /*!< Signal name */

/* GPIO_SD_B1_09 (number 10), FlexSPI_D2_A/U13[3] */
/* Routed pin properties */
#define BOARD_INITQSPIPINS_FlexSPI_D2_A_PERIPHERAL                       FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPIPINS_FlexSPI_D2_A_SIGNAL                   FLEXSPI_A_DATA2   /*!< Signal name */

/* GPIO_SD_B1_06 (number 13), FlexSPI_D3_A/U13[7] */
/* Routed pin properties */
#define BOARD_INITQSPIPINS_FlexSPI_D3_A_PERIPHERAL                       FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPIPINS_FlexSPI_D3_A_SIGNAL                   FLEXSPI_A_DATA3   /*!< Signal name */

/* GPIO_SD_B1_11 (number 8), FlexSPI_SS0/U13[1] */
/* Routed pin properties */
#define BOARD_INITQSPIPINS_FlexSPI_SS0_PERIPHERAL                        FLEXSPI   /*!< Peripheral name */
#define BOARD_INITQSPIPINS_FlexSPI_SS0_SIGNAL                    FLEXSPI_A_SS0_B   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitQSPIPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
